#!/bin/bash
echo "KILL"
echo "314674" | sudo -S  killall -SIGKILL  apt
sudo killall -SIGKILL  apt-get
echo ""
echo "AUTOPURGE"
sudo apt-get autopurge
echo ""
echo "AUTOREMOVE"
sudo apt-get autoremove
echo ""
echo "AUTOCLEAN"
sudo apt-get autoclean
echo ""
echo "CLEAN"
sudo apt-get clean

echo ""
echo "FINISH CLEAN"



