#!/usr/bin/env python3

import sys

def join_hash(input_file, output_file):
    with open(input_file, 'r') as f:
        lines = f.readlines()

    # Join all lines into a single line
    one_line_hash = ''.join([line.strip() for line in lines])

    with open(output_file, 'w') as f:
        f.write(one_line_hash)

    print(f"Hash written to {output_file}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: join_hash.py <input_file>")
        sys.exit(1)

    input_file = sys.argv[1]
    output_file =sys.argv[1]

    join_hash(input_file, output_file)
