#!/usr/bin/env python3
import sys
from gtts import gTTS
import os
import subprocess

# Join all arguments into a single string, space-separated
input_text = ' '.join(sys.argv[1:])

# Create a gTTS object
tts = gTTS(text=input_text, lang='iw')  # Change 'en' to your preferred language

# Save to mp3
tts.save("output.mp3")
with open('/dev/null', 'w') as FNULL:
    subprocess.call(['mpg321', 'output.mp3'], stdout=FNULL, stderr=subprocess.STDOUT)
