#! /usr/bin/env python3
import os
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("port", help="FORMAT: soclisten port")
args = parser.parse_args()

command="socat TCP-L:{} ".format(args.port)+"FILE:`tty`,raw,echo=0"

print(command)
os.system(command)
