#!/usr/bin/env python3
import os
import re
import argparse
import sys

# Set up command line argument parser
parser = argparse.ArgumentParser(description="accept directory only to search text in files in it")
parser.add_argument("location", help="The directory to search in.")
parser.add_argument("search_term", help="The word or pattern to search for.")
parser.add_argument("-p", "--pattern", action="store_true", help="Treat search_term as a regular expression pattern.")

# Parse command line arguments
args = parser.parse_args()

blue_color = "\033[94m"
yellow_color = "\033[93m"
reset_color = "\033[0m"

loc = args.location
search = args.search_term

print("searching:", search)
print("location:", loc)

x=0
# Walk through the directory, including subdirectories
for dirpath, dirnames, filenames in os.walk(loc):
    for filename in filenames:
        # Construct the full file path
        filepath = os.path.join(dirpath, filename)

        try:
            # Open the file and search for the search_term
            with open(filepath, 'r') as file:
                for line in file:
                    colored_title = blue_color + "line: " + reset_color + line.strip()
                    colored_filepath = yellow_color + "file: " + reset_color + filepath

                    # If -p/--pattern is specified, use re.search
                    if args.pattern and re.search(search, line):
                        print(colored_title + " " + colored_filepath + "\n")
                        x+=1
                    # Otherwise, check for an exact word match
                    elif not args.pattern and search in line.split():
                        print(colored_title + " " + colored_filepath + "\n")
                        x+=1
        except KeyboardInterrupt:
            print("Stop searching, quitting")
            sys.exit(1)
        except:
            pass


