#!/bin/bash

# Check if correct number of arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <service_name> <on|off>"
    exit 1
fi

# Assign arguments to variables
service_name=$1
action=$2

# Function to enable and start a service
enable_start_service() {
    echo '314674' | sudo -S  systemctl enable "$service_name"
    echo '314674' | sudo -S  systemctl start "$service_name"
    echo "Service $service_name has been enabled and started."
}

# Function to disable and stop a service
disable_stop_service() {
    echo '314674' | sudo -S  systemctl stop "$service_name"
    echo '314674' | sudo -S  systemctl disable "$service_name"
    echo "Service $service_name has been stopped and disabled."
}


case "$action" in
    on)
        enable_start_service
        ;;
    off)
        disable_stop_service
        ;;
    *)
        echo "Invalid action. Use 'on' or 'off'."
        exit 1
        ;;
esac