#!/bin/bash

# Check if the input argument is provided
if [ -z "$1" ]; then
    echo "Usage: $0 <file or directory>"
    exit 1
fi

# Function to download subtitles
download_subs() {
    local pathi=$1
    local lang=$2
    local encoding_flag=$3

    if [ -d "$pathi" ]; then
        file_type_message="directory"
    fi

    echo -e "\033[1;32mSearching $lang subtitles for the file: $pathi\033[0m"
    subliminal download -f "$pathi" -l "$lang"  --provider opensubtitles --provider opensubtitlesvip --provider podnapisi  --provider tvsubtitles $encoding_flag 2>/dev/null 
}

# Determine if the input is a file or directory and process accordingly
if [ -f "$1" ]; then
    # Handle file
    download_subs "$1" "en" ""
    download_subs "$1" "heb" "-e UTF-8"
    echo -e "\033[1;32mTranslate subtitles\033[0m"
    trf -f "$1"
elif [ -d "$1" ]; then
    # Handle directory
    cd "$1"
    for video_file in *.{mkv,mp4,avi,ts}; do
        if [ -f "$video_file" ]; then
            download_subs "$video_file" "en" ""
            download_subs "$video_file" "heb" "-e UTF-8"
        fi
    done
    visubs "$1"
    echo -e "\033[1;32mTranslate subtitles for directory\033[0m"
    trf -d "$1"
    visubs "$1"
else
    echo "Error: '$1' is neither a file nor a directory."
    exit 1
fi

status=$?
if [ $status -eq 0 ]; then
    echo "Operation complete"
    exit 0
else
    exit 1
fi
